language: php


# Commands you want to run that will verify your build.
script: find . -name \*.php -exec php -l "{}" \; | grep 'PHP Parse error'

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always
