language: php

php:
  - 5.3
  - hhvm

before_install:
  - travis_retry composer self-update
install:
  - travis_retry composer install --no-interaction --prefer-source

# Commands you want to run that will verify your build.
script: phpunit

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  allow_failures:
    - php: 5.3
    - php: hhvm
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always
